### ISSUE TITLE
最終課題の内容説明

### ISSUE THREAD

**Issue by makora9143** [t18701sf/final#1]
一応授業で，「 README.mdを作成して，その中に最終課題の内容をかく．」
という指示をしていると思うので，それを守って，最終課題の内容を書いてください．

**Comment by t18701sf** [comment]
返信遅れてすいません。
分かりました。ありがとうございます。

**Comment by t18701sf** [comment]
こんにちは。
僕の最終課題はhtmlが多数ありまして、それをターミナルからgithubにログインする事が出来ないのですが、どうすれば良いでしょうか。

**Comment by makora9143** [comment]
ちょっとどういう状態なのかわからないので、もう少し説明をするか、直接質問に来てください！
#4 
@tanimutomo

**Comment by t18701sf** [comment]
返信ありがとうございます。
もう一度詳しく説明します。僕の最終課題はhtmlファイル（final1.html~final5.html）が5つ存在します。
授業中にfinal.shogo.htmlといった基盤となるhtmlファイルと、final.js・READ.MEの3つはgithubに入れれています。僕的にはその他のhtmlファイルとcssを同じgithubのファイルの中に入れたいのですが、その作業が完了しません。
デスクトップの同じファイルに全てまとめ、cd、ls、addなどをしているのですが出来ません。
ターミナルに何を打ち込めばgithubの同じところに全てを入れる事が出来るのでしょうか。すいませんが教えてください。よろしくお願いします。

**Comment by tanimutomo** [comment]
そういうことですね．
でしたら，実際に見せていただかないことには，解決することが難しそうなので，本日の授業で見せてください．
